export const LOGIN_GOOGLE = "LOGIN_GOOGLE";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAILURE = "LOGIN_GOOGLE_FAILURE";
export const IS_LOGINED = "IS_LOGINED";
